export const Routes = {
  WelcomeScreen: 'WelcomeScreen',
  SignUp: 'SignUp',
  userSignUpDetails: 'userSignUpDetails',
  LogIn: 'LogIn',
  ForgotPassword: 'ForgotPassword',
  OtpVerification: 'OtpVerification',
  ResetPassword: 'ResetPassword',
  HistoryTab: 'HistoryTab',
  HomeTab: 'HomeTab',
  DynamicScreen: 'DynamicScreen',
  AppIntro: 'AppIntro',
  Profile: 'Profile',
  FAQS: 'FAQS',
  ManageProfile: 'ManageProfile',
  PrivacyProfile: 'PrivacyProfile',
  TermsAndCondition: 'TermsAndCondition',
  Notification: 'Notification',
  TrackingTab: 'TrackingTab',
  Visits: 'Visits',
  TeleHealthScreen: 'TeleHealthScreen',
  IntroStack: 'IntroStack',
  AuthStack: 'AuthStack',
  BottomTabs: 'BottomTabs',
};
